### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by 7sharp9** [fsprojects/atom-fsharp#55] opened 2015-06-03 09:12 UTC
[Enter steps to reproduce below:]

1. Open atom with the F# plugin installed

**Atom Version**: 0.205.0
**System**: Mac OS X 10.10.3
**Thrown From**: [atom-fsharp](https://github.com/fsprojects/atom-fsharp) package, v0.4.8

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /Users/dave/.atom/packages/atom-fsharp/lib/fsharp.js:135

TypeError: Cannot read property 'length' of undefined
    at Array__Length$String_1String (/Users/dave/.atom/packages/atom-fsharp/lib/fsharp.js:135:14)
    at Array__TryPickIndexedAux$String_1_String_1String_String (/Users/dave/.atom/packages/atom-fsharp/lib/fsharp.js:200:15)
    at Array__TryPickIndexed$String_1_String_1String_String (/Users/dave/.atom/packages/atom-fsharp/lib/fsharp.js:196:12)
    at Array__TryFind$String_1String (/Users/dave/.atom/packages/atom-fsharp/lib/fsharp.js:179:12)
    at proj (/Users/dave/.atom/packages/atom-fsharp/lib/fsharp.js:710:25)
    at /Users/dave/.atom/packages/atom-fsharp/lib/fsharp.js:751:33
    at FSReqWrap.oncomplete (fs.js:77:15)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "whitespace",
      "autocomplete",
      "layout-manager",
      "highlight-selected",
      "language-ocaml",
      "atom-fsharp-grammar"
    ],
    "themes": [
      "atom-dark-ui",
      "chemical-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-fsharp, v0.4.8
chemical-syntax, v0.0.1
language-csharp, v0.5.0
language-elixir, v0.5.0
pretty-json, v0.3.3

# Dev
No dev packages
```

**Comment by Bomret** [comment] 2015-06-07 10:26
Can reproduce.

**Atom Version**: 0.207.0
**System**: Mac OS X 10.10.3
**Thrown From**: [atom-fsharp](https://github.com/fsprojects/atom-fsharp) package, v0.4.9


### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /Users/stefanreichel/.atom/packages/atom-fsharp/lib/fsharp.js:136

TypeError: Cannot read property 'length' of undefined
    at Array__Length$String_1String (/Users/stefanreichel/.atom/packages/atom-fsharp/lib/fsharp.js:136:14)
    at Array__TryPickIndexedAux$String_1_String_1String_String (/Users/stefanreichel/.atom/packages/atom-fsharp/lib/fsharp.js:201:15)
    at Array__TryPickIndexed$String_1_String_1String_String (/Users/stefanreichel/.atom/packages/atom-fsharp/lib/fsharp.js:197:12)
    at Array__TryFind$String_1String (/Users/stefanreichel/.atom/packages/atom-fsharp/lib/fsharp.js:180:12)
    at proj (/Users/stefanreichel/.atom/packages/atom-fsharp/lib/fsharp.js:715:25)
    at /Users/stefanreichel/.atom/packages/atom-fsharp/lib/fsharp.js:756:33
    at FSReqWrap.oncomplete (fs.js:77:15)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "go-plus"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Paket, v1.0.0
atom-fsharp, v0.4.9
language-gitignore, v0.2.0
language-rust, v0.4.3

# Dev
No dev packages
```

**Comment by Krzysztof-Cieslak** [comment] 2015-06-07 15:21
Hmm, I can't reproduce it. Can You set up minimal repo on which You can reproduce error and push it to GitHub?

**Comment by 7sharp9** [comment] 2015-06-11 07:57
Still getting this on 0.208.0

I just open atom and I get the error

**Comment by Indy9000** [comment] 2015-06-11 18:49
I get the same error.

    [Enter steps to reproduce below:]

    1. Just open atom
    

    **Atom Version**: 0.208.0
    **System**: Mac OS X 10.10.3
    **Thrown From**: [atom-fsharp](https://github.com/fsprojects/atom-fsharp) package, v0.5.4


    ### Stack Trace

    Uncaught TypeError: Cannot read property 'length' of undefined

    ```
    At /Users/indy9000/.atom/packages/atom-fsharp/lib/fsharp.js:184

    TypeError: Cannot read property 'length' of undefined
        at Array__Length$String_1String (/Users/indy9000/.atom/packages/atom-fsharp/lib/fsharp.js:184:14)
        at Array__TryPickIndexedAux$String_1_String_1String_String (/Users/indy9000/.atom/packages/atom-fsharp/lib/fsharp.js:289:15)
        at Array__TryPickIndexed$String_1_String_1String_String (/Users/indy9000/.atom/packages/atom-fsharp/lib/fsharp.js:266:12)
        at Array__TryFind$String_1String (/Users/indy9000/.atom/packages/atom-fsharp/lib/fsharp.js:245:12)
        at proj (/Users/indy9000/.atom/packages/atom-fsharp/lib/fsharp.js:849:25)
        at /Users/indy9000/.atom/packages/atom-fsharp/lib/fsharp.js:890:33
        at FSReqWrap.oncomplete (fs.js:77:15)
    ```

    ### Commands

    ```
         -2:20 window:update-available (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
         -1:18.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
    ```

    ### Config

    ```json
    {
      "core": {
        "disabledPackages": [
          "autocomplete"
        ]
      }
    }
    ```

    ### Installed Packages

    ```coffee
    # User
    atom-fsharp, v0.5.4
    language-fsharp, v0.8.4

    # Dev
    No dev packages
    ```

**Comment by tpetricek** [comment] 2015-06-11 20:55
I have seen this too - I think it might depend on whether there is some current folder opened or not (because I got this when opening Atom, but it disappeared after I opened Atom in a folder).

**Comment by WallaceKelly** [comment] 2015-06-19 15:45
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.210.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [atom-fsharp](https://github.com/fsprojects/atom-fsharp) package, v0.5.10


### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At C:\Users\Wallace\.atom\packages\atom-fsharp\lib\fsharp.js:184

TypeError: Cannot read property 'length' of undefined
    at Array__Length$String_1String (C:\Users\Wallace\.atom\packages\atom-fsharp\lib\fsharp.js:184:14)
    at Array__TryPickIndexedAux$String_1_String_1String_String (C:\Users\Wallace\.atom\packages\atom-fsharp\lib\fsharp.js:289:15)
    at Array__TryPickIndexed$String_1_String_1String_String (C:\Users\Wallace\.atom\packages\atom-fsharp\lib\fsharp.js:266:12)
    at Array__TryFind$String_1String (C:\Users\Wallace\.atom\packages\atom-fsharp\lib\fsharp.js:245:12)
    at proj (C:\Users\Wallace\.atom\packages\atom-fsharp\lib\fsharp.js:908:25)
    at C:\Users\Wallace\.atom\packages\atom-fsharp\lib\fsharp.js:949:33
    at FSReqWrap.oncomplete (fs.js:77:15)
```

### Commands

```
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by 7sharp9** [comment] 2015-06-26 06:48
I got this just now, just updated the plugin with 3 doc tabs open, an unsaved one, settings, and a find one.

```
TypeError: Cannot read property 'length' of undefined
  at Array__Length$String_1String (/Users/dave/.atom/packages/atom-fsharp/lib/fsharp.js:188:14)
  at Array__TryPickIndexedAux$String_1_String_1String_String (/Users/dave/.atom/packages/atom-fsharp/lib/fsharp.js:320:15)
  at Array__TryPickIndexed$String_1_String_1String_String (/Users/dave/.atom/packages/atom-fsharp/lib/fsharp.js:297:12)
  at Array__TryFind$String_1String (/Users/dave/.atom/packages/atom-fsharp/lib/fsharp.js:276:12)
  at proj (/Users/dave/.atom/packages/atom-fsharp/lib/fsharp.js:1028:25)
  at /Users/dave/.atom/packages/atom-fsharp/lib/fsharp.js:1073:33
  at FSReqWrap.oncomplete (fs.js:77:15)
```

**Comment by forki** [comment] 2015-06-29 08:10
same here.

**Comment by AntyaDev** [comment] 2015-07-30 21:29
same here

**Comment by panesofglass** [comment] 2015-08-26 15:06
I just got this with 0.12.8.

**Comment by panesofglass** [comment] 2015-08-26 15:10
I don't get the error if I open a project folder. This could be a problem only when the editor has no content loaded.

**Comment by Krzysztof-Cieslak** [comment] 2015-09-03 09:23
*Should* be fixed in `0.12.11`. Would appreciate testing by any of Mac users :)

**Comment by rasmuskl** [comment] 2015-09-03 17:47
1. Installed 0.12.12
2. Error :-(

**Atom Version**: 1.0.7
**System**: Microsoft Windows 10 Pro N
**Thrown From**: [atom-fsharp](https://github.com/fsprojects/atom-fsharp) package, v0.12.12


### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At C:\Users\rasmuskl\.atom\packages\atom-fsharp\lib\fsharp.js:195

TypeError: Cannot read property 'length' of undefined
  at Array__Length$String_1String (C:\Users\rasmuskl\.atom\packages\atom-fsharp\lib\fsharp.js:195:14)
  at Array__TryPickIndexedAux$String_1_String_1String_String (C:\Users\rasmuskl\.atom\packages\atom-fsharp\lib\fsharp.js:351:15)
  at Array__TryPickIndexed$String_1_String_1String_String (C:\Users\rasmuskl\.atom\packages\atom-fsharp\lib\fsharp.js:328:12)
  at Array__TryFind$String_1String (C:\Users\rasmuskl\.atom\packages\atom-fsharp\lib\fsharp.js:307:12)
  at proj (C:\Users\rasmuskl\.atom\packages\atom-fsharp\lib\fsharp.js:1260:25)
  at C:\Users\rasmuskl\.atom\packages\atom-fsharp\lib\fsharp.js:1329:33
  at FSReqWrap.oncomplete (fs.js:77:15)

```

### Commands

```
     -9:23.7.0 window:update-available (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -8:09.2.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -7:07.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -6:34.4.0 core:backspace (div.settings-view.pane-item)
```

### Config

```json
{
  "core": {},
  "atom-fsharp": {}
}
```

### Installed Packages

```coffee
# User
atom-fsharp, v0.12.12
color-picker, v2.0.11
docblockr, v0.7.3
emmet, v2.3.12
minimap, v4.13.2
minimap-pigments, v0.1.6
pigments, v0.13.2

# Dev
No dev packages
```

**Comment by Krzysztof-Cieslak** [comment] 2015-09-03 18:05
Random bug fixing attempt 3, version `0.12.13`

**Comment by rasmuskl** [comment] 2015-09-03 19:29
@Krzysztof-Cieslak `0.12.13` fixed the issue for me. I can now Disable / Enable. That threw the error before.

**Comment by Krzysztof-Cieslak** [comment] 2015-09-03 19:32
Sounds good. Would be nice if someone with Mac also confirm that it's fixed.

**Comment by rasmuskl** [comment] 2015-09-03 20:18
I can test on my work mac tomorrow and see if I get errors.

**Comment by Krzysztof-Cieslak** [comment] 2015-09-03 20:32
Cool, thanks :)

**Comment by rasmuskl** [comment] 2015-09-04 09:41
@Krzysztof-Cieslak Tested on my Macbook Pro running OSX 10.10.5 Yosemite - installed `0.12.13`. No errors.

**Comment by Krzysztof-Cieslak** [comment] 2015-09-04 09:42
Amazing, thanks :)

**Closed by Krzysztof-Cieslak** 2015-09-04 09:42 UTC
